name: ci
on:
  push: 
    branches:
      - main

permissions: 
  checks: write
  contents: read
  
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        
      - name: Dotnet Setup
        uses:  actions/setup-dotnet@v5
        with: 
          dotnet-version: '9.0.x'
        
      - name: Build Project
        run: dotnet build telegram-killer.API
        
      - name: Run Tests
        run: dotnet test tests/telegram-killer.API.IntegrationTests --logger trx --results-directory test-results --verbosity detailed
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: test-results/**/*.trx